Excuser/WebApplication1/Models/Category.cs
using System.Collections.Generic;

namespace WebApplication1.Models
{
	public class Category
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public  List<Subcategory> Subcategories { get; set; }
	}
}

Excuser/WebApplication1/Models/CustomizeFormRequest.cs
using System.Collections.Generic;
using WebApplication1.Infrastrcuture.Utils;

namespace WebApplication1.Models
{
	public class CustomizeFormRequest
	{
		public CustomizeFormRequest(string categoryName, List<Subcategory> subcategories, List<Keyword> keywords, List<string> tones)
		{
			CategoryName = categoryName;
			Subcategories = subcategories;
			Keywords = keywords;
			Tones = tones; 
		}
		public string CategoryName { get; set; }
		public List<Subcategory> Subcategories { get; set; }
		public List<Keyword> Keywords { get; set; }
		public List<string> Tones { get; set; }
	}
}

Excuser/WebApplication1/Models/Excuse.cs
using System.Collections.Generic;
using WebApplication1.Infrastrcuture.Utils;

namespace WebApplication1.Models
{
	public class Excuse
	{
		public int Id { get; set; }
		public string Body { get; set; }
		public Tone Tone { get; set; }
		public int SubcategoryId { get; set; }
		public Subcategory Subcategory { get; set; }
		public IList<ExcuseKeyword> ExcuseKeywords { get; set; }
	}
}

Excuser/WebApplication1/Models/ExcuseKeyword.cs
namespace WebApplication1.Models
{
	public class ExcuseKeyword
	{
		public int ExcuseId { get; set; }
		public Excuse Excuse { get; set; }
		public int KeywordId { get; set; }
		public Keyword Keyword { get; set; }
	}
}

Excuser/WebApplication1/Models/ExcuseRequest.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebApplication1.Infrastrcuture.Utils;

namespace WebApplication1.Models
{
	public class ExcuseRequest
	{
		[Required]
		public int SubcategoryId { get; set; }
		public List<int> ExcludedExcuseIds { get; set; } = new List<int>();
		[StringLength(15, ErrorMessage = "Name length can't be more than 15 characters.")]
		public string Name { get; set; }
		[Required]
		public Tone Tone { get; set; }
		public List<int> KeywordIds { get; set; }
	}
}

Excuser/WebApplication1/Models/ExcuseResponse.cs
namespace WebApplication1.Models
{
	public class ExcuseResponse
	{
		public int? Id { get; set; }
		public string Name { get; set; }
		public string Body { get; set; }
	}
}

Excuser/WebApplication1/Models/Keyword.cs
using System.Collections.Generic;

namespace WebApplication1.Models
{
	public class Keyword
	{
		public int Id { get; set; }
		public string Value { get; set; }
		public IList<ExcuseKeyword> ExcuseKeywords { get; set; }
	}
}

Excuser/WebApplication1/Models/Subcategory.cs
namespace WebApplication1.Models
{
	public class Subcategory
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public int CategoryId { get; set; }
		public virtual Category Category { get; set; }
	}
}

Excuser/WebApplication1/Models/Tone.cs
namespace WebApplication1.Infrastrcuture.Utils
{
	public enum Tone
	{
		Polite = 0, 
		Friendly = 1
	}
}

Excuser/WebApplication1/Controllers/CustomizeFormController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Infrastrcuture.Utils;
using WebApplication1.Models;
using WebApplication1.Service;

namespace WebApplication1.Controllers
{
	public class CustomizeFormController : Controller
	{
		private readonly ICategoryService _categoryService;
		private readonly IKeywordService _keywordService;
		private readonly IExcuseService _excuseService;

		public CustomizeFormController(ICategoryService categoryService, IKeywordService keywordService, IExcuseService excuseService)
		{
			_categoryService = categoryService;
			_keywordService = keywordService;
			_excuseService = excuseService;
		}

		public IActionResult Index(int categoryId = 4)
		{
			ViewBag.Subcategories = _categoryService.GetAllSubcategories(categoryId).ToList();
			ViewBag.Keywords = _keywordService.GetAllKeywords().ToList();
			ViewBag.Tones = Enum.GetNames(typeof(Tone)).ToList();
			ViewBag.CategoryName = _categoryService.GetCatgoryName(categoryId);
			return View();
		}
		[Route("/CustomizeForm/PostForm/")]
		[HttpPost]
		public IActionResult PostForm(ExcuseRequest request)
		{
			var excuse = _excuseService.GetMatchingExcuseOrDefault(request);
			ViewBag.Id = excuse.Id;
			ViewBag.Name = excuse.Name;
			ViewBag.Body = excuse.Body;
			return View("ExcuseResponseView");
		}

		[Route("/CustomizeForm/GenerateForm/")]
		[HttpPost]
		public IActionResult GenerateForm([FromBody] ExcuseRequest request)
		{	
			var excuse = _excuseService.GetMatchingExcuseOrDefault(request);
			ViewBag.Id = excuse.Id;
			ViewBag.Name = excuse.Name;
			ViewBag.Body = excuse.Body;
			return View("ExcuseResponseView");
		}
	}
}

Excuser/WebApplication1/Controllers/ExcuseResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class ExcuseResultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Excuser/WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Service;

namespace WebApplication1.Controllers
{
	public class HomeController : Controller
	{
		private readonly ICategoryService _categoryService;

		public HomeController(ICategoryService categoryService)
		{
			_categoryService = categoryService; 
		}
		public IActionResult Index()
		{
			var categories = _categoryService.GetAllCategories();
			return View(categories);
		}
	}
}

Excuser/WebApplication1/Views/CustomizeForm/ExcuseResponseView.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/Layout.cshtml";
    ViewBag.Title = "Excuse";
    ViewBag.Yellow = true;
}
<main>
    <section class="top width">
        <a href="/CustomizeForm/Index" class="back">Back</a>
        @if (string.IsNullOrEmpty(ViewBag.Name))
        {
            <h2>Finish up excuse</h2>
        }
        else
        {
            <h2>Finish up excuse for @ViewBag.Name</h2>
        }
       <p>Click on words to see suggestions!</p>
    </section>

    <section class="two-container width">
        <section class="big">
            <div id="resultText" class="rounded">@ViewBag.Body</div>
        </section>
            
        <section class="small">
            <a class="button rounded left-align noedit" onclick="copyToClipboard()"><span class="icon copy"></span>Copy to clipboard</a>
            <a class="button rounded left-align margintop-1 white noedit" onclick="sendEmail()"><span class="icon email"></span>Send as an email</a>
            <a class="button rounded left-align margintop-1 white noedit" onclick="GenerateAnotherExcuse(@ViewBag.Id)"><span class="icon new"></span>Generate new one</a>
            <a class="button rounded left-align margintop-1 white noedit" href="/home/index"><span class="icon start"></span>Start over</a>
        </section>
    </section>
</main>

<script src="/Scripts/result.js"></script>
<script>
    const cat = localStorage.getItem("category").toLowerCase()
    document.getElementsByTagName("BODY")[0].classList.add(cat)
</script>

Excuser/WebApplication1/Views/CustomizeForm/Index.cshtml
@using WebApplication1.Models
@model ExcuseRequest
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/Layout.cshtml";
    ViewBag.Title = ViewBag.CategoryName;
    ViewBag.Yellow = true;
}
<main>
    <form asp-controller="CustomizeForm" asp-action="PostForm" method="post">
        <section class="top width">
            <a href="/" class="back">Back</a>
            <h2>Cook your excuse for @ViewBag.CategoryName.ToString().ToLower()</h2>
        </section>
        <section class="two-container width">
            <section class="small">
                <div class="input-box">
                    <label for="subcategory">
                        Select the subcategory
                    </label>
                    <select id="subcategoryId" required="" asp-for="SubcategoryId">
                     @foreach (Subcategory sub in ViewBag.Subcategories)
                        {
                            <option value="@sub.Id">@sub.Name</option>
                        }
                    </select>
                </div>
                <div class="input-box margintop">
                    <label asp-for="Name">
                        Who is it for? <span>- optional</span>
                    </label>
                    <input id="person" asp-for="Name" placeholder="try John..." maxlength="15">
                </div>
                <div class="input-box2 margintop">
                    <label for="sliderTone">
                        Select the tone of your excuse
                    </label>
                    <div class="slidecontainer">
                        <input type="hidden" asp-for="KeywordIds" />
                        <input type="range" min="0" max="1" value="0" class="slider" asp-for="Tone">
                        <p>
                            @foreach (string tone in ViewBag.Tones)
                            {
                                <span>@tone</span>
                            }

                        </p>
                    </div>
                </div>
            </section>

            <section class="big">
                <div class="input-box">
                    <label for="tags">
                        Describe your situation with keywords
                    </label>
                    <div class="tag-box" id="tagBox"><input type="text" id="tagsInput" class="not" placeholder='Separate by "space"' list="availableKeywords"></div>
                    <datalist id="availableKeywords">
                        @foreach (Keyword keyword in ViewBag.Keywords)
                        {
                            <option value="@keyword.Value" data-id="@keyword.Id" />
                        }

                    </datalist>
                    <!-- <textarea id="tags" placeholder='Separate by "space"'></textarea> -->
                </div>
                <p>Please really do separate by space and check for typos. For the list of keywords we work with, check this.</p>
            </section>
        </section>
        <section class="button-right width">
            <input type="submit" id="formButton" class="button rounded margintop" value="Excuse me?!" />
        </section>
    </form>
</main>
<script src="/Scripts/form.js"></script>
<script>
    localStorage.removeItem("category")
    localStorage.setItem("category", "@ViewBag.CategoryName")
</script>

Excuser/WebApplication1/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/Layout.cshtml";
    ViewBag.Title = "Homepage";
    ViewBag.Yellow = false;
}
@using WebApplication1.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model  IEnumerable<WebApplication1.Models.Category>

<main>
    <section class="hero">
        <section class="hero--container width">
            <h1>I was late 'cause my dog ate shit...</h1>
            <p class="nomargin">Is this <span>really</span> your excuse? You can do better!</p>
            <a href="#categories" class="button rounded margintop zfix">Create excuse</a>
        </section>
    </section>
    <section class="categories width" id="categories">
        <h2>Step up your excuse game</h2>
        <p class="nomargin">with only two more clicks!</p>
        <section class="categories--container">
            @foreach (Category category in Model)
            {
                <a class="category @category.Name.ToLower()" asp-controller="CustomizeForm" asp-action="Index" asp-route-categoryId="@category.Id"><span class="rounded">@category.Name</span></a>
            }
        </section>
    </section>
</main>

Excuser/WebApplication1/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <link href="/Styles/css/style.css" rel="stylesheet" />
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>@ViewBag.Title | Excuser</title>
    </head>
    <body class="@ViewBag.Title.ToString().ToLower() @if (ViewBag.Yellow == true) { @(" yellow") }">
        <header>
            <nav class="width">
                <a href="/" class="logo" type="button">
                    Excuser
                </a>
                <button class="avatar"></button>
            </nav>
        </header>

        @RenderBody()
    </body>
</html>